name: Docker
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Docker build (and optional push)
    runs-on: ubuntu-18.04
    env:
      SWAPBROWSER_VERSION: 3.2.31
      SWAP_VERSION: 3.0.3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-SwapBrowser-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-SwapBrowser-org
    - name: Install and start services (needed for image test)
      run: docker-compose up -d
    - name: build, test and optionally push docker image
      run: ./script/build_docker.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx
