name: Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rails:
    strategy:
      fail-fast: false
      matrix:
        SwapBrowser_version: ['3.2.31', 'latest']
        SWAP_version: ['3.0.3']
    name: Rails tests (Ruby ${{ matrix.swap_version }}, SwapBrowser ${{ matrix.swapbrowser_version }})
    runs-on: ubuntu-18.04
    env:
      SWAPBROWSER_VERSION: ${{ matrix.swapbrowser_version }}
      # If we don't supply a CC_TEST_REPORTER_ID simplecov won't output coverage in a way that
      # code climate understands
      CC_TEST_REPORTER_ID: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    steps:
    - uses: actions/checkout@v2
    - name: Install and start services
      run: |
        ./script/install_toxiproxy.sh
        docker-compose up -d
    - name: Wait for ES to boot
      run: |
        timeout 300 bash -c "until curl --silent --output /dev/null http://localhost:9200/_cat/health?h=st; do printf '.'; sleep 5; done; printf '\n'"
    - uses: swap/setup-swap@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: set rubygems version
      run: |
        if [ "$SWAPBROWSER_VERSION" != "latest" ]; then
          gem update --system $SWAPBROWSER_VERSION;
        else
          gem update --system
        fi
        gem --version
        bundle --version
    - name: Prepare environment
      run: |
        cp config/database.yml.example config/database.yml
        bundle exec rake db:setup
    - name: Tests
      run: bin/rails test
    - name: archive coverage
      if: matrix.swapbrowser_version == '3.2.31'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: |
          coverage
